##
## This code was generated by snekrpc. Do not edit.
## Generated: 2026-01-25T14:07:09.970657-05:00
##

from datetime import datetime, timezone
from typing import Any, Iterable

import msgspec

import snekrpc


class Command(msgspec.Struct):
    name: str
    arguments: dict[str, Any]


class Event(msgspec.Struct):
    name: str
    message: str
    timestamp: datetime = msgspec.field(
        default_factory=lambda: datetime.now().astimezone(timezone.utc)
    )


class Service:
    def __init__(self, proxy: snekrpc.service.ServiceProxy):
        self._proxy = proxy

    def chunk(self) -> 'bytes':
        res = self._proxy.chunk()
        return msgspec.convert(res, type=bytes)

    def command(self, command: 'Command') -> 'None':
        self._proxy.command(command)

    def download(self) -> 'Iterable[bytes]':
        res = self._proxy.download()
        for r in res:
            yield msgspec.convert(r, type=Iterable[bytes].__args__[0])  # type: ignore

    def echo(self, value: 'Any') -> 'Any':
        res = self._proxy.echo(value)
        return msgspec.convert(res, type=Any)

    def event(self) -> 'Event':
        res = self._proxy.event()
        return msgspec.convert(res, type=Event)

    def events(self) -> 'Iterable[Event]':
        res = self._proxy.events()
        for r in res:
            yield msgspec.convert(r, type=Iterable[Event].__args__[0])  # type: ignore

    def upload(self, data: 'Iterable[bytes]') -> 'None':
        self._proxy.upload(data)


class Client(snekrpc.Client):
    @property
    def example(self) -> Service:
        proxy = self.service('example')
        return Service(proxy)
